<a href="https://colab.research.google.com/github/Daniel-AMN/Projetos/blob/main/ProcessoSeletivoBix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib as plt

In [2]:
vendas = pd.read_csv("/content/Base de Dados - Question치rio.xlsx - Sheet1.csv",decimal=',')
produtos = pd.read_csv("/content/Base de Dados - Question치rio.xlsx - Sheet2.csv")
consumidores = pd.read_csv("/content/Base de Dados - Question치rio.xlsx - Sheet3.csv")
lojas = pd.read_csv("/content/Base de Dados - Question치rio.xlsx - Sheet4.csv")

In [3]:
vendas.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,ID,ProductID,ClientID,Discount,UnitPrice,Quantity,StoreID,Date
4,NaN,NaN,80260d682079b6090c8285b398c50d97,002552c0663708129c0019cc97552d7d3,14001,"0,08","249,2",1,4,12/10/2018

In [4]:
vendaslimpo = vendas.drop(columns=['Unnamed: 0', 'Unnamed: 1'])

In [5]:
vendaslimpo

,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ID,ProductID,ClientID,Discount,UnitPrice,Quantity,StoreID,Date
4,80260d682079b6090c8285b398c50d97,002552c0663708129c0019cc97552d7d3,14001,"0,08","249,2",1,4,12/10/2018
...,...,...,...,...,...,...,...,...
32752,b155e2a8589d40bc9c0381ee48e3204f,002ec297b1b00fb9dde7ee6ac24b67712,28694,"0,08","218,4",1,4,12/2/2018
32753,abb71d0110c4be1a1a0c52f929cab4a3,002d4ea7c04739c130bb74d7e7cd16943,28694,"0,08",210,1,4,12/5/2018
32754,db9a034f34174edd577b9f64cc982952,001795ec6f1b187d37335e1c4704762e3,28694,"0,08","148,4",1,4,8/1/2019
32755,ee00fa5093eb96d8573403b382fb60a8,002ec297b1b00fb9dde7ee6ac24b67713,28694,"0,1","218,4",2,4,11/25/2019
32756,56c87d433bb46c7862e35e791b1907fa,0009406fd7479715e4bef61dd91f24622,28695,"0,1","254,8",1,4,7/4/2018

In [6]:
vendaslimpo = vendaslimpo.rename(columns=vendaslimpo.iloc[3])

In [7]:
vendaslimpo = vendaslimpo.drop(index =[0,1,2,3])

In [8]:
vendaslimpas = vendaslimpo.reset_index(drop = True)

In [9]:
vendaslimpas

,ID,ProductID,ClientID,Discount,UnitPrice,Quantity,StoreID,Date
0,80260d682079b6090c8285b398c50d97,002552c0663708129c0019cc97552d7d3,14001,"0,08","249,2",1,4,12/10/2018
1,3275736da1234f55d52bdf09d86b93bc,001b237c0e9bb435f2e54071129237e93,14001,"0,1","162,4",1,4,4/25/2019
2,f3513eec8f1434b5b7e04ddf3598df40,00066f42aeeb9f3007548bb9d3f33c381,14001,"0,1","194,6",1,4,7/17/2019
3,7180475b60fe6bbbde424d39704a1177,001b72dfd63e9833e8c02742adf472e33,14002,"0,1","201,6",2,1,4/10/2018
4,76600853a200fe87e141adae6b35674c,00210e41887c2a8ef9f791ebc780cc363,14002,"0,1",406,1,1,1/21/2019
...,...,...,...,...,...,...,...,...
32748,b155e2a8589d40bc9c0381ee48e3204f,002ec297b1b00fb9dde7ee6ac24b67712,28694,"0,08","218,4",1,4,12/2/2018
32749,abb71d0110c4be1a1a0c52f929cab4a3,002d4ea7c04739c130bb74d7e7cd16943,28694,"0,08",210,1,4,12/5/2018
32750,db9a034f34174edd577b9f64cc982952,001795ec6f1b187d37335e1c4704762e3,28694,"0,08","148,4",1,4,8/1/2019
32751,ee00fa5093eb96d8573403b382fb60a8,002ec297b1b00fb9dde7ee6ac24b67713,28694,"0,1","218,4",2,4,11/25/2019
32752,56c87d433bb46c7862e35e791b1907fa,0009406fd7479715e4bef61dd91f24622,28695,"0,1","254,8",1,4,7/4/2018

In [10]:
vendaslimpas.head()

,ID,ProductID,ClientID,Discount,UnitPrice,Quantity,StoreID,Date
0,80260d682079b6090c8285b398c50d97,002552c0663708129c0019cc97552d7d3,14001,"0,08","249,2",1,4,12/10/2018
1,3275736da1234f55d52bdf09d86b93bc,001b237c0e9bb435f2e54071129237e93,14001,"0,1","162,4",1,4,4/25/2019
2,f3513eec8f1434b5b7e04ddf3598df40,00066f42aeeb9f3007548bb9d3f33c381,14001,"0,1","194,6",1,4,7/17/2019
3,7180475b60fe6bbbde424d39704a1177,001b72dfd63e9833e8c02742adf472e33,14002,"0,1","201,6",2,1,4/10/2018
4,76600853a200fe87e141adae6b35674c,00210e41887c2a8ef9f791ebc780cc363,14002,"0,1",406,1,1,1/21/2019

In [11]:
vendaslimpas["Discount"]= vendaslimpas["Discount"].str.replace(',','.')
vendaslimpas["UnitPrice"]= vendaslimpas["UnitPrice"].str.replace(',','.')

In [12]:
vendaslimpas = vendaslimpas.astype({'UnitPrice': float, 'Discount': float, 'Quantity' : int})

In [13]:
vendaslimpas["DiscountValue"] = vendaslimpas["UnitPrice"] * vendaslimpas["Discount"]

In [14]:
vendaslimpas

,ID,ProductID,ClientID,Discount,UnitPrice,Quantity,StoreID,Date,DiscountValue
0,80260d682079b6090c8285b398c50d97,002552c0663708129c0019cc97552d7d3,14001,0.08,249.2,1,4,12/10/2018,19.936
1,3275736da1234f55d52bdf09d86b93bc,001b237c0e9bb435f2e54071129237e93,14001,0.10,162.4,1,4,4/25/2019,16.240
2,f3513eec8f1434b5b7e04ddf3598df40,00066f42aeeb9f3007548bb9d3f33c381,14001,0.10,194.6,1,4,7/17/2019,19.460
3,7180475b60fe6bbbde424d39704a1177,001b72dfd63e9833e8c02742adf472e33,14002,0.10,201.6,2,1,4/10/2018,20.160
4,76600853a200fe87e141adae6b35674c,00210e41887c2a8ef9f791ebc780cc363,14002,0.10,406.0,1,1,1/21/2019,40.600
...,...,...,...,...,...,...,...,...,...
32748,b155e2a8589d40bc9c0381ee48e3204f,002ec297b1b00fb9dde7ee6ac24b67712,28694,0.08,218.4,1,4,12/2/2018,17.472
32749,abb71d0110c4be1a1a0c52f929cab4a3,002d4ea7c04739c130bb74d7e7cd16943,28694,0.08,210.0,1,4,12/5/2018,16.800
32750,db9a034f34174edd577b9f64cc982952,001795ec6f1b187d37335e1c4704762e3,28694,0.08,148.4,1,4,8/1/2019,11.872
32751,ee00fa5093eb96d8573403b382fb60a8,002ec297b1b00fb9dde7ee6ac24b67713,28694,0.10,218.4,2,4,11/25/2019,21.840
32752,56c87d433bb46c7862e35e791b1907fa,0009406fd7479715e4bef61dd91f24622,28695,0.10,254.8,1,4,7/4/2018,25.480

In [15]:
vendaslimpas["SalePrice"] = (vendaslimpas["UnitPrice"] - vendaslimpas["DiscountValue"]) * vendaslimpas["Quantity"]

In [16]:
vendaslimpas

,ID,ProductID,ClientID,Discount,UnitPrice,Quantity,StoreID,Date,DiscountValue,SalePrice
0,80260d682079b6090c8285b398c50d97,002552c0663708129c0019cc97552d7d3,14001,0.08,249.2,1,4,12/10/2018,19.936,229.264
1,3275736da1234f55d52bdf09d86b93bc,001b237c0e9bb435f2e54071129237e93,14001,0.10,162.4,1,4,4/25/2019,16.240,146.160
2,f3513eec8f1434b5b7e04ddf3598df40,00066f42aeeb9f3007548bb9d3f33c381,14001,0.10,194.6,1,4,7/17/2019,19.460,175.140
3,7180475b60fe6bbbde424d39704a1177,001b72dfd63e9833e8c02742adf472e33,14002,0.10,201.6,2,1,4/10/2018,20.160,362.880
4,76600853a200fe87e141adae6b35674c,00210e41887c2a8ef9f791ebc780cc363,14002,0.10,406.0,1,1,1/21/2019,40.600,365.400
...,...,...,...,...,...,...,...,...,...,...
32748,b155e2a8589d40bc9c0381ee48e3204f,002ec297b1b00fb9dde7ee6ac24b67712,28694,0.08,218.4,1,4,12/2/2018,17.472,200.928
32749,abb71d0110c4be1a1a0c52f929cab4a3,002d4ea7c04739c130bb74d7e7cd16943,28694,0.08,210.0,1,4,12/5/2018,16.800,193.200
32750,db9a034f34174edd577b9f64cc982952,001795ec6f1b187d37335e1c4704762e3,28694,0.08,148.4,1,4,8/1/2019,11.872,136.528
32751,ee00fa5093eb96d8573403b382fb60a8,002ec297b1b00fb9dde7ee6ac24b67713,28694,0.10,218.4,2,4,11/25/2019,21.840,393.120
32752,56c87d433bb46c7862e35e791b1907fa,0009406fd7479715e4bef61dd91f24622,28695,0.10,254.8,1,4,7/4/2018,25.480,229.320

In [17]:
ReceitaLiquida = vendaslimpas[['SalePrice','Date']]

In [18]:
ReceitaLiquida['Date'] = pd.to_datetime(ReceitaLiquida['Date'])

<ipython-input-18-9ae80854f85b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ReceitaLiquida['Date'] = pd.to_datetime(ReceitaLiquida['Date'])

In [19]:
ReceitaLiquida['Year'] = ReceitaLiquida['Date'].dt.year

<ipython-input-19-1acb9231b538>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ReceitaLiquida['Year'] = ReceitaLiquida['Date'].dt.year

In [35]:
ReceitaLiquida2019 = ReceitaLiquida.drop('Date', axis = 1)

In [37]:
ReceitaLiquida2019['Year'].value_counts()

2018    17254
2019    14768
2020      731
Name: Year, dtype: int64

In [38]:
ReceitaLiquida2019 = ReceitaLiquida2019.astype({'Year': int})

In [41]:
ReceitaLiquida2019 = ReceitaLiquida2019.loc[ReceitaLiquida2019['Year'] == 2019]

In [44]:
ReceitaLiquida2019.describe()

          SalePrice     Year
count  14768.000000  14768.0
mean     239.110315   2019.0
std      155.245294      0.0
min      103.320000   2019.0
25%      146.160000   2019.0
50%      192.780000   2019.0
75%      229.320000   2019.0
max     1262.240000   2019.0

In [23]:
prodfreq = vendaslimpas['ProductID'].value_counts()

In [24]:
prodfreq['002d4ea7c04739c130bb74d7e7cd16943']

963

In [25]:
consumidores.head()

      ID            City State DateOfBirth     Sex
0  14001        Curitiba    PR   6/28/1985   Homem
1  14002   Florian칩polis    SC   1/10/1987   Homem
2  14003  Rio de Janeiro    RJ   11/5/1979   Homem
3  14004  Rio de Janeiro    RJ  11/25/1983  Mulher
4  14005   Florian칩polis    SC    4/7/1969   Homem

In [45]:
consumidores['State'].value_counts()

SC    3459
RJ    2844
RS    2554
PR    2132
SP    1509
MG     763
BH     352
ES       7
MT       6
MA       4
RO       4
GO       3
BA       3
RN       3
AC       3
RR       2
PA       1
MS       1
Name: State, dtype: int64

In [26]:
lojas.head()

   ID            Name State
0   1   Florian칩polis    SC
1   2  Rio de Janeiro    RJ
2   3    Porto Alegre    RS
3   4        Curitiba    PR
4   7       S칚o Paulo    SP

In [27]:
produtos

                                   ID             Name Size
0   00066f42aeeb9f3007548bb9d3f33c381  Capit칚o Am칠rica    P
1   00066f42aeeb9f3007548bb9d3f33c382  Capit칚o Am칠rica    M
2   00066f42aeeb9f3007548bb9d3f33c383  Capit칚o Am칠rica    G
3   00088930e925c41fd95ebfe695fd26551             Thor    P
4   00088930e925c41fd95ebfe695fd26552             Thor    M
..                                ...              ...  ...
68  0030e635639c898b323826589761cf233       Rick Morty    G
69  003128f981470c3e5a2e7445e4a771cd1   Homer Simpsons    P
70  003128f981470c3e5a2e7445e4a771cd2   Homer Simpsons    M
71  003128f981470c3e5a2e7445e4a771cd3   Homer Simpsons    G
72  003128f981470c3e5a2e7445e4a771cd4   Homer Simpsons   GG

[73 rows x 3 columns]

In [28]:
produtos.head()

                                  ID             Name Size
0  00066f42aeeb9f3007548bb9d3f33c381  Capit칚o Am칠rica    P
1  00066f42aeeb9f3007548bb9d3f33c382  Capit칚o Am칠rica    M
2  00066f42aeeb9f3007548bb9d3f33c383  Capit칚o Am칠rica    G
3  00088930e925c41fd95ebfe695fd26551             Thor    P
4  00088930e925c41fd95ebfe695fd26552             Thor    M

In [29]:
produtos.describe()

                                       ID            Name Size
count                                  73              73   73
unique                                 73              24    4
top     00066f42aeeb9f3007548bb9d3f33c381  Homer Simpsons    P
freq                                    1               4   24

In [30]:
completo = pd.merge(produtos,vendaslimpas,'outer')

In [31]:
completo

,ID,Name,Size,ProductID,ClientID,Discount,UnitPrice,Quantity,StoreID,Date,DiscountValue,SalePrice
0,00066f42aeeb9f3007548bb9d3f33c381,Capit칚o Am칠rica,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00066f42aeeb9f3007548bb9d3f33c382,Capit칚o Am칠rica,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00066f42aeeb9f3007548bb9d3f33c383,Capit칚o Am칠rica,G,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00088930e925c41fd95ebfe695fd26551,Thor,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00088930e925c41fd95ebfe695fd26552,Thor,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
32821,b155e2a8589d40bc9c0381ee48e3204f,NaN,NaN,002ec297b1b00fb9dde7ee6ac24b67712,28694,0.08,218.4,1.0,4,12/2/2018,17.472,200.928
32822,abb71d0110c4be1a1a0c52f929cab4a3,NaN,NaN,002d4ea7c04739c130bb74d7e7cd16943,28694,0.08,210.0,1.0,4,12/5/2018,16.800,193.200
32823,db9a034f34174edd577b9f64cc982952,NaN,NaN,001795ec6f1b187d37335e1c4704762e3,28694,0.08,148.4,1.0,4,8/1/2019,11.872,136.528
32824,ee00fa5093eb96d8573403b382fb60a8,NaN,NaN,002ec297b1b00fb9dde7ee6ac24b67713,28694,0.10,218.4,2.0,4,11/25/2019,21.840,393.120
32825,56c87d433bb46c7862e35e791b1907fa,NaN,NaN,0009406fd7479715e4bef61dd91f24622,28695,0.10,254.8,1.0,4,7/4/2018,25.480,229.320